### ISSUE TITLE
TFT rotation and Touch coordinates

### ISSUE THREAD

**Issue by maitredede** [JoaoLopesF/SPFD5408#6]
Hi,

When using the paint sample, I can see that screen rotation is not the same that touch rotation : I touch horizontaly (left to right), it draws verticaly (bottom to top).
If I `tft.setRotation(1)`, coords are good.

How can I have touch and screen rotation have matching coords ?

Thanks.

**Comment by JoaoLopesF** [comment]
Hi,

In mine TFTs I need invert the coords.
Can be in your case it not necessary.

Please modify the SPFD5408_TouchScreen, line 159:

before:

   //return TSPoint(x, y, z);

   // **\* SPFD5408 change -- Begin
   // SPFD5408 change, because Y coordinate is inverted in this controller
   return TSPoint(x, 1023 - y, z);
   // -- End

after:

   return TSPoint(x, y, z);

   // **\* SPFD5408 change -- Begin
   // SPFD5408 change, because Y coordinate is inverted in this controller
   //return TSPoint(x, 1023 - y, z);
   // -- End
